### ISSUE TITLE
config for pyproject.toml

### ISSUE THREAD

**Issue by jdhao** [jgosmann/pylint-venv#17]
This is what is working for me:

```toml
[tool.pylint.main]
init-hook ="""
try:
  import pylint_venv
except ImportError:
  pass
else:
  pylint_venv.inithook()
"""
```

The config in readme does not work due to parsing issues. Test on pylint 2.17.2

**Comment by jgosmann** [comment]
The config in the README is intended for the `.pylintrc` file, not `pyproject.toml`. Did you verify that there is indeed a problem with the given `.pylintrc` config independent of configuration via `pyproject.toml`?

**Comment by Ash8888** [comment]
> This is what is working for me:

Thanks jdhao, this worked for me as well.

> The config in the README is intended for the .pylintrc file, not pyproject.toml.

Maybe classifying this issue as a documentation request (rather then a parsing error) is the way to go? I'm not sure how ubiquitous pyproject.toml is becoming elsewhere, but I am using it on new projects. I appreciate that I could cut & paste the code provided rather then having to translate .pylintrc to .toml - I don't work with .pylintrc very often. It would be better if I was cutting and pasting from an official source instead of an issue report. imho.

**Comment by jgosmann** [comment]
@Ash8888 fair point, would you be willing to prepare a PR?
